### ISSUE TITLE
forjj-gitlab binary is in the code

### ISSUE THREAD

**Issue by clarsonneur** [forj-oss/forjj-gitlab#2]
Hi,

The repo contains the forjj-gitlab binary. This is not a good place for such files.

I think you need to fix it by removing it and update the gitignore to avoid those files to be added.

As this binary is small, this is not so critical, as the git history won't be so strong. But usually, we need to remove those files from the history as well, which is changing all the repository.

**Comment by clarsonneur** [comment]
If you want I can do the cleanup for you to update the history.

**Comment by Xx-Parks-xX** [comment]
I do this with good practices
